dist: trusty
sudo: false
language: c
os:
  - linux
compiler: gcc-5
env:
  global:
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: Marvim's Github access token
    - secure: N73UKR9bIcAh5q+YXdru8iWdMJh6V85PMtl14ZK4EzTi1MP8AcSuTEJMOAizGOcYL+jL7tM/Kd8rxsJVYcwdqIPij4jugNsm4UZLgxAoI1rZ2wpUHAqQdknTFGzss64UuNehbcEM82aK5/qbtvzU3eM8UVVVsuTg8SvB+XAmdI4=
    # COVERITY_SCAN_TOKEN
    - secure: pgI3Qt7bCRDeuKX38hP9xTJ6CdbwoUkcPToHnfDFYeclhUJRgCfZhCKKO+zTwqoa2Jx7wShoFeHaKidOFctg4ls4lrn47b0bPFED3LtU7RDQaeamqFKzgTV1IcEpkUfGl/i8tOmaEd7UvyUHKuKZmjmVr4Ce4ugATShYB186EW0=
  matrix:
    - CI_TARGET=nightly
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install bash;
      brew install jq;
      brew install gettext;
      brew reinstall -s libtool;
    fi
script:
  - ./ci/${CI_TARGET}.sh
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - bzr-fastimport
      - clang-3.9
      - cmake
      - g++-5
      - gcc-5
      - gdb
      - libtool
      - llvm-3.9-dev
      - pkg-config
      - unzip
      - xclip
cache:
  apt: true
  directories:
    - "${TRAVIS_BUILD_DIR}/.deps/build/src"

notifications:
  email:
    on_success: never
