language: c
compiler: gcc
env:
  global:
    - GIT_NAME="marvim"
    - GIT_EMAIL="marvim@users.noreply.github.com"
    - NEOVIM_REPO=neovim/neovim
    - NEOVIM_BRANCH=master
    - MAKE_CMD="make -j2"
    - BUILD_DIR=${TRAVIS_BUILD_DIR}
    - NEOVIM_DIR=${BUILD_DIR}/build/neovim
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    - secure: G13kwiQU0GY+/H9Zf+shujRr/RP2tVcf9u6cdT6t9GLl8YzNDWz1NDLA0Ykh/kkYht9Bw36diPFcNsHVCs8KwZJcEWS5L2b9g5Cv9VzU7RyQE1uc+oBn2tbDamYUjMkhRGtvrTdVdpjyoQr2mhx5rh7KmOz5VDahLti5cR9yEAU=
  matrix:
    - TRAVIS_BUILD_TYPE=coverity
    - TRAVIS_BUILD_TYPE=rebuild-docs
    - TRAVIS_BUILD_TYPE=rebuild-deps
script:
  - ./travis.sh
