language: c
os:
  - linux
env:
  global:
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: Marvim's Github access token
    - secure: OyoqXO0CqQJpxggE0tNi6LeYXGHslw4SSe4u3UbTOali5AbKdRnSxkMz9YQiuEajJDI2//LZef6RVLULFPZqzIOzsr4yi9S1fbPhXHvqtnZOkpamnkXNNCf7Fd6vGJtT1W140YR9woQoSk0bcLepawSdtkgp+n/ZSqY8rvADgqw=
    # COVERITY_SCAN_TOKEN
    - secure: pgI3Qt7bCRDeuKX38hP9xTJ6CdbwoUkcPToHnfDFYeclhUJRgCfZhCKKO+zTwqoa2Jx7wShoFeHaKidOFctg4ls4lrn47b0bPFED3LtU7RDQaeamqFKzgTV1IcEpkUfGl/i8tOmaEd7UvyUHKuKZmjmVr4Ce4ugATShYB186EW0=
  matrix:
    - CI_TARGET=assign-labels
    - CI_TARGET=clang-report
    - CI_TARGET=coverity
    - CI_TARGET=deps32
    - CI_TARGET=deps64
    - CI_TARGET=doc-index
    - CI_TARGET=doxygen
    - CI_TARGET=nightly
    - CI_TARGET=sync-mirrors
    - CI_TARGET=translation-report
    - CI_TARGET=user-docu
    - CI_TARGET=vimpatch-report
matrix:
  include:
    - os: osx
      env: CI_TARGET=deps64
      compiler: gcc-4.9
  allow_failures:
    - env: CI_TARGET=coverity
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install bash;
    fi
script:
  - ./ci/${CI_TARGET}.sh
notifications:
  email:
    on_success: never
